// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package proto.greet;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.greet.GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.greet.Greeting greeting = 1;</code>
   * @return Whether the greeting field is set.
   */
  boolean hasGreeting();
  /**
   * <code>.proto.greet.Greeting greeting = 1;</code>
   * @return The greeting.
   */
  proto.greet.Greeting getGreeting();
  /**
   * <code>.proto.greet.Greeting greeting = 1;</code>
   */
  proto.greet.GreetingOrBuilder getGreetingOrBuilder();
}
